add /zip directory and COSMOPOLITAN_DISABLE_ZIPOS
also try to build vim and emacs

diff --git a/emacs-28.2/superconfigure b/emacs-28.2/superconfigure
--- a/emacs-28.2/superconfigure
+++ b/emacs-28.2/superconfigure
@@ -1,12 +1,48 @@
 #!/usr/bin/env bash
+set -e
+shopt -s expand_aliases
 
-# edit src/config.in to change 
-#   INTERRUPT_INPUT to INTERRUPT_INPUT0
-#   USABLE_FIONREAD to USABLE_FIONREAD0
+# check for cosmo dirs
+if [ -z ${COSMO+x} ]; then 
+    echo "could not find COSMO source directory!";
+    exit 1
+fi
 
+if [ -z ${COSMOS+x} ]; then 
+    echo "could not find COSMOS install directory!";
+    exit 1
+fi
+
+alias strip=$STRIP
+alias ar=$AR
+FOLDER="emacs-28.2"
+
+if [[ -f sources.tar.gz ]]; then
+    # we already downloaded it
+    cd $FOLDER
+    make -s -i clean
+    cd ..
+else
+    # download the source code
+    wget -q https://ftp.gnu.org/gnu/emacs/emacs-28.2.tar.gz -O sources.tar.gz
+    tar -xzf sources.tar.gz
+
+    # apply patches if any
+    patch -p0 -i minimal.diff
+fi
+
+# go into the source folder, configure
+cd $FOLDER
 ./configure --without-x --without-gnutls\
     --disable-acl --with-threads\
     --with-sound=no --with-unexec=no\
     --without-gpm --without-modules --without-libgmp\
+    --sysconfdir=/zip --datarootdir=/zip/share --exec-prefix=/zip/$ARCH\
     --prefix=$COSMOS\
     CFLAGS="-Os -I$COSMOS/include/ncurses"
+
+# run make and/or make install
+make -s -j2
+make install -s -j2
+
+echo "DONE."
diff --git a/vim-9.0.1670/superconfigure b/vim-9.0.1670/superconfigure
--- a/vim-9.0.1670/superconfigure
+++ b/vim-9.0.1670/superconfigure
@@ -1,8 +1,37 @@
 #!/usr/bin/env bash
+set -e
+shopt -s expand_aliases
 
-export LDFLAGS=-L/opt/cosmos/lib
-export CFLAGS=-I/opt/cosmos/include
+# check for cosmo dirs
+if [ -z ${COSMO+x} ]; then 
+    echo "could not find COSMO source directory!";
+    exit 1
+fi
 
+if [ -z ${COSMOS+x} ]; then 
+    echo "could not find COSMOS install directory!";
+    exit 1
+fi
+
+alias strip=$STRIP
+alias ar=$AR
+FOLDER="vim-9.0.1670"
+
+if [[ -f sources.tar.gz ]]; then
+    # we already downloaded it
+    cd $FOLDER
+    make -s -i clean
+    cd ..
+else
+    # download the source code
+    wget -q https://github.com/vim/vim/archive/refs/tags/v9.0.1670.tar.gz -O sources.tar.gz
+    tar -xzf sources.tar.gz
+
+    # apply patches if any
+    # patch -p0 -i minimal.diff
+fi
+
+# go into the source folder, configure
 ./configure --disable-darwin --disable-smack --disable-selinux\
     --disable-xsmp --enable-luainterp=no --enable-perlinterp=no\
     --enable-pythoninterp=no --enable-python3interp=no\
@@ -13,5 +42,12 @@ export CFLAGS=-I/opt/cosmos/include
     --disable-canberra --disable-libsodium\
     --without-x --with-tlib=tinfo\
     --with-local-dir=$COSMOS/lib\
+    --sysconfdir=/zip --datarootdir=/zip/share --exec-prefix=/zip/$ARCH\
     --prefix=$COSMOS\
-    CFLAGS="-Os"
+    CFLAGS="-Os -I$COSMOS/include" LDFLAGS="-L$COSMOS/lib" 
+
+# run make and/or make install
+make -s -j2
+make install -s -j2
+
+echo "DONE."
