update config

diff --git a/gdbm-1.23/superconfigure b/gdbm-1.23/superconfigure
--- a/gdbm-1.23/superconfigure
+++ b/gdbm-1.23/superconfigure
@@ -1,5 +1,26 @@
 #!/usr/bin/env bash
+set -e
 
+# check for cosmo dirs
+if [ -z ${COSMO+x} ]; then 
+    echo "could not find COSMO source directory!";
+    exit 1
+fi
+
+if [ -z ${COSMOS+x} ]; then 
+    echo "could not find COSMOS install directory!";
+    exit 1
+fi
+
+# download the source code
+wget https://ftp.gnu.org/gnu/gdbm/gdbm-1.23.tar.gz -O sources.tar.gz
+tar -xzf sources.tar.gz
+
+# apply patches if any
+# patch -p0 -i
+
+# go into the source folder, configure
+cd gdbm-1.23/
 export COMPATINCLUDEDIR="$COSMOS/include/gdbm"
 
 ./configure --prefix="$COSMOS"\
@@ -8,3 +29,9 @@ export COMPATINCLUDEDIR="$COSMOS/include/gdbm"
     --disable-nls --disable-rpath\
     --without-pic --with-gnu-ld --without-readline\
     CFLAGS="-Os"
+
+# run make and/or make install
+make -j2
+make install -j2
+
+echo "DONE."
diff --git a/libuuid-1.0.3/superconfigure b/libuuid-1.0.3/superconfigure
--- a/libuuid-1.0.3/superconfigure
+++ b/libuuid-1.0.3/superconfigure
@@ -1,6 +1,33 @@
 #!/usr/bin/env bash
+set -e
 
+# check for cosmo dirs
+if [ -z ${COSMO+x} ]; then 
+    echo "could not find COSMO source directory!";
+    exit 1
+fi
+
+if [ -z ${COSMOS+x} ]; then 
+    echo "could not find COSMOS install directory!";
+    exit 1
+fi
+
+# download the source code
+wget https://sourceforge.net/projects/libuuid/files/libuuid-1.0.3.tar.gz/download -O sources.tar.gz
+tar -xzf sources.tar.gz
+
+# apply patches if any
+# patch -p0 -i
+
+# go into the source folder, configure
+cd libuuid*/
 ./configure --enable-static --disable-shared\
     --without-pic --with-gnu-ld\
     --prefix="$COSMOS"\
     CFLAGS="-Os"
+
+# run make and/or make install
+make -j2
+make install -j2
+
+echo "DONE."
diff --git a/wget-1.21/superconfigure b/wget-1.21/superconfigure
--- a/wget-1.21/superconfigure
+++ b/wget-1.21/superconfigure
@@ -1,17 +1,44 @@
 #!/usr/bin/env bash
+set -e
+
+# check for cosmo dirs
+if [ -z ${COSMO+x} ]; then 
+    echo "could not find COSMO source directory!";
+    exit 1
+fi
+
+if [ -z ${COSMOS+x} ]; then 
+    echo "could not find COSMOS install directory!";
+    exit 1
+fi
+
+# download the source code
+wget https://ftp.gnu.org/gnu/wget/wget-1.21.tar.gz -O sources.tar.gz
+tar -xzf sources.tar.gz
+
+# apply patches if any
+# disable all the checks in fseeko.c, and just call cosmo's fseeko
+# remove the FALLTHROUGH macro if there is a complaint
+patch -p0 -i minimal.diff
+
+# go into the source folder, configure
+cd wget*/
 
 export OPENSSL_CFLAGS=""
 export OPENSSL_LIBS="-lssl -lcrypto"
 
-# disable all the checks in fseeko.c, and just call cosmo's fseeko
-# remove the FALLTHROUGH macro if there is a complaint
-
 ./configure --prefix="$COSMOS"\
-    --with-ssl=openssl\
-    --with-openssl=yes --disable-ipv6\
+    --with-ssl=openssl --with-openssl=yes\
     --without-pic --with-gnu-ld\
     --disable-shared --enable-static\
     --enable-threads=posix --disable-rpath\
     --disable-xattr --disable-nls\
     --without-plugin-support\
+    --sysconfdir=/zip\
     CFLAGS="-Os" LIBS="-lbrotlidec -lbrotlienc -lbz2 -lz -llzma"
+
+# run make and/or make install
+make -j2
+make install -j2
+
+echo "DONE."
diff --git a/xz-5.4.3/superconfigure b/xz-5.4.3/superconfigure
--- a/xz-5.4.3/superconfigure
+++ b/xz-5.4.3/superconfigure
@@ -1,8 +1,35 @@
 #!/usr/bin/env bash
+set -e
 
+# check for cosmo dirs
+if [ -z ${COSMO+x} ]; then 
+    echo "could not find COSMO source directory!";
+    exit 1
+fi
+
+if [ -z ${COSMOS+x} ]; then 
+    echo "could not find COSMOS install directory!";
+    exit 1
+fi
+
+# download the source code
+wget https://sourceforge.net/projects/lzmautils/files/xz-5.4.3.tar.gz/download -O sources.tar.gz
+tar -xzf sources.tar.gz
+
+# apply patches if any
+# patch -p0 -i
+
+# go into the source folder, configure
+cd xz-5.4.3/
 ./configure --prefix="$COSMOS"\
     --enable-shared=no --enable-static=yes\
     --disable-nls --disable-rpath\
     --without-pic --with-gnu-ld\
     --enable-sandbox=no\
     CFLAGS="-Os -std=gnu99"
+
+# run make and/or make install
+make -j2
+make install -j2
+
+echo "DONE."
